name: TODO_package_name

channels:
  - default
  - conda-forge

dependencies:
  - python>=3.10
  - pandas>=1.4.2
  - jupyter
  - ipython
  - pylint
  - invoke
  - joblib
  - black
  - nb_black
  - pre-commit
  - pip
  - pip:
    - -e .
